#!/bin/bash
# Generates fixFirstAgentWeb/static/config.js from SSM Parameter Store values.
# Usage: ./scripts/generate-config.sh [app-name]
#   app-name defaults to "fixFirstAgent"

set -euo pipefail

# Prevent Git Bash (MSYS) from converting /forward-slash arguments to Windows paths
export MSYS_NO_PATHCONV=1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

APP_NAME="${1:-fixFirstAgent}"

# Determine the AWS region: use explicit env var, CLI default, or fall back to us-west-2
if [ -n "${AWS_REGION:-}" ]; then
  DEPLOY_REGION="${AWS_REGION}"
elif [ -n "${AWS_DEFAULT_REGION:-}" ]; then
  DEPLOY_REGION="${AWS_DEFAULT_REGION}"
else
  DEPLOY_REGION=$(aws configure get region 2>/dev/null || echo "us-west-2")
fi
export AWS_REGION="${DEPLOY_REGION}"

echo "Fetching configuration from SSM Parameter Store (prefix: /${APP_NAME}, region: ${DEPLOY_REGION})..."

REGION=$(aws ssm get-parameter --name "/${APP_NAME}/region" --region "${DEPLOY_REGION}" --query 'Parameter.Value' --output text)
COGNITO_USER_POOL_ID=$(aws ssm get-parameter --name "/${APP_NAME}/cognito-user-pool-id" --region "${DEPLOY_REGION}" --query 'Parameter.Value' --output text)
COGNITO_CLIENT_ID=$(aws ssm get-parameter --name "/${APP_NAME}/cognito-client-id" --region "${DEPLOY_REGION}" --query 'Parameter.Value' --output text)
AGENTCORE_RUNTIME_ARN=$(aws ssm get-parameter --name "/${APP_NAME}/agentcore-runtime-arn" --region "${DEPLOY_REGION}" --query 'Parameter.Value' --output text)

CONFIG_FILE="fixFirstAgentWeb/static/config.js"

cat > "${CONFIG_FILE}" <<EOF
// Auto-generated by scripts/generate-config.sh — do not edit manually.
const APP_CONFIG = {
  REGION: '${REGION}',
  COGNITO_USER_POOL_ID: '${COGNITO_USER_POOL_ID}',
  COGNITO_CLIENT_ID: '${COGNITO_CLIENT_ID}',
  AGENTCORE_RUNTIME_ARN: '${AGENTCORE_RUNTIME_ARN}'
};
EOF

echo "Config written to ${CONFIG_FILE}"
echo "  REGION:                 ${REGION}"
echo "  COGNITO_USER_POOL_ID:   ${COGNITO_USER_POOL_ID}"
echo "  COGNITO_CLIENT_ID:      ${COGNITO_CLIENT_ID}"
echo "  AGENTCORE_RUNTIME_ARN:  ${AGENTCORE_RUNTIME_ARN}"
